Repository buildo/scriptoni, pull requests merged in 2018-12, with the labels that each got.

#232 #231: TypeError: Cannot read property 'ts' of undefined (closes #231)
  package.json
  test/globalSetup.js
Labels: bug, waiting for merge

#236 #235: upgrade metarpheus-io-ts (closes #235)
  package.json
  test/__snapshots__/metarpheus.test.ts.snap
  test/stylelint.test.ts
Labels: breaking, waiting for merge

#240 Avoid using '' as model prelude default
  src/model.ts
  src/scripts/metarpheus/config.ts
Labels: bug
