Repository buildo/scriptoni, pull requests merged in 2018-05, with the labels that each got.

#191 add webpack tests
  .drone.yml
  jest.config.js
  package.json
  test/__snapshots__/webpack.test.ts.snap
  test/template-app/.babelrc
  test/template-app/.eslintrc
  test/template-app/.gitignore
  test/template-app/.stylelintrc
  test/template-app/config/Config.js
  test/template-app/config/development.json
  test/template-app/config/production.json
  test/template-app/package.json
  test/template-app/src/API/API.ts
  test/template-app/src/API/index.ts
  test/template-app/src/commands/commands.ts
  test/template-app/src/commands/index.ts
  test/template-app/src/components/App/App.tsx
  test/template-app/src/components/App/app.scss
  test/template-app/src/components/App/index.ts
  test/template-app/src/components/Dropdown/Dropdown.ts
  test/template-app/src/components/Dropdown/dropdown.scss
  test/template-app/src/components/Dropdown/index.ts
  test/template-app/src/components/Hello/Hello.tsx
  test/template-app/src/components/Hello/hello.scss
  test/template-app/src/components/Hello/index.ts
  test/template-app/src/components/SwitchViewDropdown/SwitchViewDropdown.tsx
  test/template-app/src/components/SwitchViewDropdown/index.ts
  test/template-app/src/components/View/View.ts
  test/template-app/src/components/View/index.ts
  test/template-app/src/index.html
  test/template-app/src/locales/en.json
  test/template-app/src/locales/it.json
  test/template-app/src/model/index.ts
  test/template-app/src/queries/index.ts
  test/template-app/src/queries/queries.ts
  test/template-app/src/setup/addDeviceClassName.js
  test/template-app/src/setup/index.js
  test/template-app/src/setup/loadLocale.js
  test/template-app/src/setup/polyfills.js
  test/template-app/src/theme/index.ts
  test/template-app/src/theme/main.scss
  test/template-app/src/theme/typography.scss
  test/template-app/src/theme/variables.scss
  test/template-app/tsconfig.json
  test/template-app/yarn.lock
  test/webpack.test.ts
  tsconfig.json
Labels: in review

#192 #189: wrong babelrc in monorepo with shared folders (closes #189)
  src/scripts/webpack/paths.js
  src/scripts/webpack/webpack.base.js
Labels: bug, waiting for merge

#194 #193: metarpheus config file path should be overridable (closes #193)
  jest.config.js
  src/scripts/metarpheus-diff/index.js
  src/scripts/metarpheus/config.js
  src/scripts/metarpheus/index.js
  src/scripts/metarpheus/run.js
  src/scripts/webpack/tsconfig.json
  test/globalSetup.js
  test/metarpheus.test.ts
  test/template-app/fake-api-src/Account.scala
  test/template-app/metarpheus.config.test.js
  test/utils.ts
  test/webpack.test.ts
Labels: in review

#197 #169: can we remove the "clean react" step from every build? (closes #169)
  bin/scriptoni.js
Labels: defect, waiting for merge

#200 Improve tests build
  test/__snapshots__/webpack.test.ts.snap
  test/globalSetup.js
  test/runCommands.js
  test/utils.ts
Labels: waiting for merge
