Repository buildo/scriptoni, pull requests merged in 2018-03, with the labels that each got.

#171 #170: Build breaks if you remove ie11 from browsers (.babelrc) (closes #170)
  package.json
  src/scripts/webpack/webpack.build.js
Labels: bug, waiting for merge

#173 #172: upgrade metarpheus-io-ts to get newtypes support (closes #172)
  package.json
Labels: WIP, breaking

#175 #174: Bump metarpheus and metarpheus-io-ts version (closes #174)
  package.json
Labels: WIP

#176 #76: Webpack extendable configuration (closes #76)
  README.md
  src/scripts/webpack/build-ts.js
  src/scripts/webpack/build.js
  src/scripts/webpack/compiler.js
  src/scripts/webpack/dev-ts.js
  src/scripts/webpack/dev.js
Labels: waiting for merge

#179 #178: uglifyed build output does not work on IE11 and Chrome 38 (closes #178)
  src/scripts/webpack/webpack.build.js
Labels: bug, waiting for merge
