Repository buildo/scriptoni, pull requests merged in 2019-01, with the labels that each got.

#246 Remove stylelint
  README.md
  copy-files.ts
  package.json
  src/index.ts
  src/scripts/stylelint/index.ts
  src/scripts/stylelint/stylefmt.ts
  src/scripts/stylelint/stylelintrc.json
  src/scripts/webpack/webpack.base.ts
  test/stylelint.test.ts
  test/template-app/.stylelintrc
Labels: breaking

#250 #234: Scriptoni does not log errors (closes #234)
  src/index.ts
  src/util.ts
Labels: bug, in review

#257 Webpack: stricter default tsconfig (closes #258)
  src/scripts/webpack/tsconfig.json
  test/template-app/src/components/SwitchViewDropdown/SwitchViewDropdown.tsx
Labels: breaking

#255 #130: [webpack] no devtool in dev and prod by default (closes #130)
  src/model.ts
  src/scripts/webpack/config.ts
  src/scripts/webpack/webpack.build.ts
  test/__snapshots__/webpack.test.ts.snap
Labels: breaking, in review

#263 #262: both scriptoni and VSCode ignore project's `.prettier.js` (closes #262)
  .prettierrc.js
  bin/scriptoni-ts.js
  bin/scriptoni.js
  copy-files.ts
  src/index.ts
  src/model.ts
  src/scripts/prettier/.prettierrc.js
  src/scripts/prettier/getDefaultArgs.ts
  src/util.ts
  test/globalSetup.js
  test/metarpheus.test.ts
  test/runCommands.js
  test/template-app/src/components/App/App.tsx
  test/template-app/src/components/Dropdown/dropdown.scss
  test/template-app/src/components/Hello/Hello.tsx
  test/template-app/src/components/Hello/hello.scss
  test/template-app/src/components/SwitchViewDropdown/SwitchViewDropdown.tsx
  test/template-app/src/theme/main.scss
  test/template-app/src/theme/typography.scss
  test/utils.ts
  test/webpack.test.ts
  typings/metarpheus.d.ts
  typings/progress-bar-webpack-plugin.d.ts
  typings/virtual-module-webpack-plugin.d.ts
Labels: breaking, bug, waiting for merge

#261 #259: tsconfig.json changes proposal (closes #259)
  src/scripts/webpack/tsconfig.json
Labels: waiting for merge

#265 #264: upgrade to metarpheus-io-ts 0.8.0 (closes #264)
  package.json
  test/__snapshots__/metarpheus.test.ts.snap
Labels: in review
